Output examples/demo/out/multi.gif

Set Shell bash
Set Width 1200
Set Height 500
Set FontSize 22
Set Padding 20
Set TypingSpeed 40ms

Hide
Type "PS1='$ '"
Enter
Type "clear"
Enter
Show

Type "cat examples/inputs/kaguya.txt | ./xylitol.sh choose --no-limit --page-size=8"
Enter
Sleep 1.5s

Type "x"
Sleep 700ms
Down
Sleep 400ms
Down
Sleep 400ms
Type "x"
Sleep 700ms
Down
Sleep 400ms
Type "x"
Sleep 1s
Enter
Sleep 2s
