import * from "std/text"
import * from "./mod.ab"
import * from "./help.ab"
import * from "../utils.ab"

pub fun execute_input(parameters: [Text]): Text {
    let prompt = "> "
    let placeholder = "Type here..."
    let header = ""
    let password = false

    for param in parameters {
        if param == "-h" or param == "--help" {
            print_input_help()
            exit(0)
        }
        if starts_with(param, "--prompt=") {
            prompt = slice(param, len("--prompt="))
        }
        if starts_with(param, "--placeholder=") {
            placeholder = slice(param, len("--placeholder="))
        }
        if starts_with(param, "--header=") {
            header = slice(param, len("--header="))
        }
        if param == "--password" {
            password = true
        }
    }

    const display_header = header == "" or has_ansi_escape(header) then escape_ansi(header) else "\\x1b[1m" + colored_primary(header)
    return xyl_input(prompt, placeholder, display_header, password)
}
