import * from "std/env"
import * from "../utils.ab"

pub fun print_input_help(): Null {
    const usage = ["Usage:", "./xylitol.sh", "input", "[flags]"]
    print_wrapped(usage)
    echo("")
    const title = [colored_primary("input"), "-", "Prompt", "for", "some", "input", "from", "the", "user."]
    print_wrapped(title)
    echo("")
    printf(colored_secondary("Flags:") + "\n")
    const names = [
        "-h, --help",
        "--placeholder=\"<text>\"",
        "--prompt=\"<text>\"",
        "--header=\"<text>\"",
        "--password",
    ]
    const texts = [
        "Show this help message",
        "Set the placeholder text",
        "Set the prompt text",
        "Set a header text to display above the prompt",
        "Hide input (for password entry)",
    ]
    const notes = [
        "",
        "(default: 'Type here...', needs Bash 4.0)",
        "(default: '> ')",
        "(ANSI escape supported)",
        "",
    ]
    render_help_entries(names, texts, notes)
    echo("")
}
